---
- name: Verify GCP Service Account Integration
  hosts: control
  become: true
  
  vars:
    # Construct service account email from name and project
    gcp_service_account_email: "{{ gcp_service_account_name }}@{{ gcp_project_id }}.iam.gserviceaccount.com"
  
  tasks:
    - name: Display configuration being verified
      ansible.builtin.debug:
        msg: |
          ================================================
          Verifying Configuration
          ================================================
          Project ID: {{ gcp_project_id }}
          Zone: {{ gcp_zone }}
          Service Account Name: {{ gcp_service_account_name }}
          Service Account Email: {{ gcp_service_account_email }}
          ================================================

    - name: Check if running on GCP
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/id
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: gcp_check
      failed_when: false
      changed_when: false

    - name: Get all available service accounts
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: all_sas
      when: gcp_check.status == 200
      changed_when: false
      failed_when: false

    - name: Check specific service account
      ansible.builtin.uri:
        url: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/{{ gcp_service_account_email }}/"
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: specific_sa
      when: gcp_check.status == 200
      changed_when: false
      failed_when: false

    - name: Get service account token
      ansible.builtin.uri:
        url: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/{{ gcp_service_account_email }}/token"
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: sa_token
      when: 
        - gcp_check.status == 200
        - specific_sa is defined
        - specific_sa.status == 200
      changed_when: false
      failed_when: false

    - name: Parse token response
      ansible.builtin.set_fact:
        token_data: "{{ sa_token.content | from_json }}"
      when:
        - sa_token is defined
        - sa_token.status == 200

    - name: Get VM instance name
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/name
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: vm_name
      when: gcp_check.status == 200
      changed_when: false

    - name: Get VM zone
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/zone
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: vm_zone
      when: gcp_check.status == 200
      changed_when: false

    - name: Check IP forwarding status
      ansible.builtin.command: cat /proc/sys/net/ipv4/ip_forward
      register: ip_forward
      changed_when: false

    - name: Display Service Account Information
      ansible.builtin.debug:
        msg: |
          ================================================
          SERVICE ACCOUNT VERIFICATION
          ================================================
          Running on GCP: {{ 'Yes' if gcp_check.status == 200 else 'No' }}
          {% if gcp_check.status == 200 %}
          
          INSTANCE DETAILS:
          Name: {{ vm_name.content }}
          Zone: {{ vm_zone.content.split('/')[-1] }}
          Instance ID: {{ gcp_check.content }}
          
          ALL AVAILABLE SERVICE ACCOUNTS ON VM:
          {% for sa in all_sas.content.split('\n') if sa %}
          {% if sa.strip() %}
            - {{ sa.strip() }}
          {% endif %}
          {% endfor %}
          
          CONFIGURED SERVICE ACCOUNT:
          Name: {{ gcp_service_account_name }}
          Email: {{ gcp_service_account_email }}
          Accessible: {{ 'YES ✓' if (specific_sa is defined and specific_sa.status == 200) else 'NO ✗' }}
          {% if specific_sa is defined and specific_sa.status == 200 %}
          Has Valid Token: {{ 'YES ✓' if (sa_token is defined and sa_token.status == 200) else 'NO ✗' }}
          {% if token_data is defined %}
          Token Type: {{ token_data.token_type | default('N/A') }}
          Token Expires In: {{ token_data.expires_in | default('N/A') }} seconds
          {% endif %}
          {% else %}
          
          ⚠ WARNING: Service account {{ gcp_service_account_email }} is NOT accessible!
          
          This service account is not attached to this VM.
          {% endif %}
          {% endif %}
          
          NETWORKING:
          IP Forwarding: {{ 'Enabled ✓' if ip_forward.stdout == '1' else 'Disabled ✗' }}
          
          ================================================
      when: gcp_check.status == 200

    - name: Check Kubernetes cluster status
      ansible.builtin.command: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      register: k8s_nodes
      changed_when: false
      failed_when: false

    - name: Display Kubernetes nodes
      ansible.builtin.debug:
        msg: |
          ================================================
          KUBERNETES CLUSTER STATUS
          ================================================
          {{ k8s_nodes.stdout }}
          ================================================
      when: k8s_nodes.rc == 0

    - name: Test service account token script
      ansible.builtin.command: /usr/local/bin/get-gcp-sa-token.sh
      register: token_script_test
      changed_when: false
      failed_when: false
      when: gcp_check.status == 200

    - name: Display token script test
      ansible.builtin.debug:
        msg: |
          ================================================
          SERVICE ACCOUNT TOKEN SCRIPT TEST
          ================================================
          Script exists: {{ 'Yes' if token_script_test.rc == 0 else 'No' }}
          {% if token_script_test.rc == 0 %}
          Token retrieved: {{ 'Yes ✓' if token_script_test.stdout | length > 0 else 'No ✗' }}
          Token length: {{ token_script_test.stdout | length }} characters
          {% endif %}
          ================================================
      when: token_script_test is defined

    - name: Provide summary and recommendations
      ansible.builtin.debug:
        msg: |
          ================================================
          SUMMARY
          ================================================
          {% if gcp_check.status != 200 %}
          ⚠ Not running on GCP - GCP integration disabled
          {% elif specific_sa is not defined or specific_sa.status != 200 %}
          ✗ SPECIFIC SERVICE ACCOUNT NOT ACCESSIBLE!
          
          Current situation:
          - VM has service accounts attached
          - {{ gcp_service_account_email }} is NOT one of them
          
          To fix, run from your LOCAL machine (not on this VM):
          
          gcloud compute instances set-service-account {{ vm_name.content if vm_name is defined else 'YOUR_VM' }} \
            --zone={{ vm_zone.content.split('/')[-1] if vm_zone is defined else gcp_zone }} \
            --service-account={{ gcp_service_account_email }} \
            --scopes=cloud-platform
          
          Then restart the VM:
          gcloud compute instances stop {{ vm_name.content if vm_name is defined else 'YOUR_VM' }} --zone={{ vm_zone.content.split('/')[-1] if vm_zone is defined else gcp_zone }}
          gcloud compute instances start {{ vm_name.content if vm_name is defined else 'YOUR_VM' }} --zone={{ vm_zone.content.split('/')[-1] if vm_zone is defined else gcp_zone }}
          
          Then re-run this verification playbook.
          {% else %}
          ✓ Service account {{ gcp_service_account_name }} ({{ gcp_service_account_email }}) is correctly configured!
          {% if sa_token is defined and sa_token.status == 200 %}
          ✓ Access token can be retrieved successfully
          {% endif %}
          {% endif %}
          
          {% if ip_forward.stdout != '1' %}
          ✗ IP forwarding is disabled!
          Run: echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
          {% endif %}
          
          {% if k8s_nodes.rc == 0 %}
          ✓ Kubernetes cluster is accessible
          {% endif %}
          ================================================
