---
- name: Verify GCP Service Account Integration
  hosts: control
  become: true
  
  tasks:
    - name: Check if running on GCP
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/id
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: gcp_check
      failed_when: false
      changed_when: false

    - name: Get VM service account
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: vm_sa
      when: gcp_check.status == 200
      changed_when: false

    - name: Get VM instance name
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/name
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: vm_name
      when: gcp_check.status == 200
      changed_when: false

    - name: Get VM zone
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/zone
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: vm_zone
      when: gcp_check.status == 200
      changed_when: false

    - name: Get service account scopes
      ansible.builtin.uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/scopes
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: sa_scopes
      when: gcp_check.status == 200
      changed_when: false

    - name: Check IP forwarding status
      ansible.builtin.command: cat /proc/sys/net/ipv4/ip_forward
      register: ip_forward
      changed_when: false

    - name: Display GCP VM Information
      ansible.builtin.debug:
        msg: |
          ================================================
          GCP VM INFORMATION
          ================================================
          Running on GCP: {{ 'Yes' if gcp_check.status == 200 else 'No' }}
          {% if gcp_check.status == 200 %}
          Instance Name: {{ vm_name.content }}
          Instance ID: {{ gcp_check.content }}
          Zone: {{ vm_zone.content.split('/')[-1] }}
          
          SERVICE ACCOUNT:
          Current SA: {{ vm_sa.content }}
          Expected SA: {{ gcp_service_account_email }}
          Match: {{ 'YES ✓' if vm_sa.content == gcp_service_account_email else 'NO ✗' }}
          
          Scopes:
          {{ sa_scopes.content }}
          {% endif %}
          
          NETWORKING:
          IP Forwarding: {{ 'Enabled ✓' if ip_forward.stdout == '1' else 'Disabled ✗' }}
          ================================================
      when: gcp_check.status == 200

    - name: Check Kubernetes cluster status
      ansible.builtin.command: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      register: k8s_nodes
      changed_when: false
      failed_when: false

    - name: Display Kubernetes nodes
      ansible.builtin.debug:
        msg: |
          ================================================
          KUBERNETES CLUSTER STATUS
          ================================================
          {{ k8s_nodes.stdout }}
          ================================================
      when: k8s_nodes.rc == 0

    - name: Get node provider ID
      ansible.builtin.shell: |
        kubectl get nodes -o jsonpath='{.items[0].spec.providerID}'
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      register: provider_id
      changed_when: false
      failed_when: false

    - name: Display provider ID
      ansible.builtin.debug:
        msg: |
          Node Provider ID: {{ provider_id.stdout if provider_id.rc == 0 else 'Not set (normal for single-node clusters)' }}
      when: k8s_nodes.rc == 0

    - name: Provide recommendations
      ansible.builtin.debug:
        msg: |
          ================================================
          RECOMMENDATIONS
          ================================================
          {% if gcp_check.status != 200 %}
          ⚠ Not running on GCP - GCP integration disabled
          {% elif vm_sa.content != gcp_service_account_email %}
          ✗ SERVICE ACCOUNT MISMATCH!
          
          To fix, run on your local machine:
          gcloud compute instances set-service-account {{ vm_name.content if vm_name is defined else 'YOUR_VM_NAME' }} \
            --zone={{ vm_zone.content.split('/')[-1] if vm_zone is defined else 'YOUR_ZONE' }} \
            --service-account={{ gcp_service_account_email }} \
            --scopes=cloud-platform
          
          Then reboot the VM or restart kubelet:
          sudo systemctl restart kubelet
          {% else %}
          ✓ Service account correctly configured
          {% endif %}
          
          {% if ip_forward.stdout != '1' %}
          ✗ IP forwarding is disabled!
          This may cause pod networking issues.
          
          To enable:
          echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
          {% endif %}
          ================================================
