---
- name: Install Rancher on Kubernetes
  hosts: control
  become: true
  
  vars:
    rancher_version: "2.9.3"
    cert_manager_version: "v1.14.5"
    rancher_namespace: "cattle-system"
    cert_manager_namespace: "cert-manager"
    rancher_bootstrap_password: "admin"
    
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      register: current_user_result
      changed_when: false
      become: false

    - name: Set current user fact
      ansible.builtin.set_fact:
        current_user: "{{ current_user_result.stdout }}"

    - name: Set KUBECONFIG for non-root user
      ansible.builtin.set_fact:
        kubeconfig_path: "/home/{{ current_user }}/.kube/config"
      when: current_user != "root"

    - name: Set KUBECONFIG for root
      ansible.builtin.set_fact:
        kubeconfig_path: "/etc/kubernetes/admin.conf"
      when: current_user == "root"

    - name: Display kubeconfig path
      ansible.builtin.debug:
        msg: "Using KUBECONFIG: {{ kubeconfig_path }}"

    - name: Check if Kubernetes is accessible
