---
- name: Install Rancher on Kubernetes
  hosts: control
  become: true
  
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      register: current_user_result
      changed_when: false
      become: false

    - name: Set current user fact
      ansible.builtin.set_fact:
        current_user: "{{ current_user_result.stdout }}"

    - name: Set KUBECONFIG for non-root user
      ansible.builtin.set_fact:
        kubeconfig_path: "/home/{{ current_user }}/.kube/config"
      when: current_user != "root"

    - name: Set KUBECONFIG for root
      ansible.builtin.set_fact:
        kubeconfig_path: "/etc/kubernetes/admin.conf"
      when: current_user == "root"

    - name: Display kubeconfig path
      ansible.builtin.debug:
        msg: "Using KUBECONFIG: {{ kubeconfig_path }}"

    - name: Check if Kubernetes is accessible
      ansible.builtin.command: kubectl get nodes
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: k8s_check
      changed_when: false

    - name: Display Kubernetes status
      ansible.builtin.debug:
        msg: "{{ k8s_check.stdout_lines }}"

    - name: Display Rancher hostname
      ansible.builtin.debug:
        msg: "Rancher will be accessible at: https://{{ rancher_hostname }}"

    # Install Helm
    - name: Check if Helm binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/helm
      register: helm_exists

    - name: Fail if Helm not installed
      ansible.builtin.fail:
        msg: |
          Helm is not installed. Please install it first:
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
      when: not helm_exists.stat.exists

    - name: Verify Helm installation
      ansible.builtin.command: /usr/local/bin/helm version
      register: helm_version_output
      changed_when: false

    - name: Display Helm version
      ansible.builtin.debug:
        msg: "{{ helm_version_output.stdout }}"

    # Add Helm repositories
    - name: Add Rancher Helm repository
      ansible.builtin.command: /usr/local/bin/helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_repo
      changed_when: false
      failed_when: false

    - name: Add Jetstack Helm repository
      ansible.builtin.command: /usr/local/bin/helm repo add jetstack https://charts.jetstack.io
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: jetstack_repo
      changed_when: false
      failed_when: false

    - name: Update Helm repositories
      ansible.builtin.command: /usr/local/bin/helm repo update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    # Install cert-manager
    - name: Create cert-manager namespace
      ansible.builtin.command: kubectl create namespace {{ cert_manager_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_ns
      changed_when: false
      failed_when: false

    - name: Install cert-manager CRDs
      ansible.builtin.command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Check if cert-manager is already installed
      ansible.builtin.command: /usr/local/bin/helm list -n {{ cert_manager_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_check
      changed_when: false

    - name: Install cert-manager using Helm
      ansible.builtin.shell: |
        /usr/local/bin/helm install cert-manager jetstack/cert-manager \
          --namespace {{ cert_manager_namespace }} \
          --version {{ cert_manager_version }} \
          --wait \
          --timeout 10m
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: "'cert-manager' not in certmanager_check.stdout"

    - name: Wait for cert-manager pods to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod \
          -l app.kubernetes.io/instance=cert-manager \
          -n {{ cert_manager_namespace }} \
          --timeout=300s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_ready
      retries: 3
      delay: 10
      until: certmanager_ready.rc == 0

    - name: Display cert-manager status
      ansible.builtin.command: kubectl get pods -n {{ cert_manager_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_pods
      changed_when: false

    - name: Show cert-manager pods
      ansible.builtin.debug:
        msg: "{{ certmanager_pods.stdout_lines }}"

    # Install Rancher
    - name: Create Rancher namespace
      ansible.builtin.command: kubectl create namespace {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_ns
      changed_when: false
      failed_when: false

    - name: Check if Rancher is already installed
      ansible.builtin.command: /usr/local/bin/helm list -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_check
      changed_when: false

    - name: Install Rancher using Helm
      ansible.builtin.shell: |
        /usr/local/bin/helm install rancher rancher-stable/rancher \
          --namespace {{ rancher_namespace }} \
          --set hostname={{ rancher_hostname }} \
          --set replicas=1 \
          --set bootstrapPassword={{ rancher_bootstrap_password }} \
          --version {{ rancher_version }} \
          --wait \
          --timeout 15m
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: "'rancher' not in rancher_check.stdout"

    - name: Wait for Rancher deployment to be ready
      ansible.builtin.command: kubectl rollout status deploy/rancher -n {{ rancher_namespace }} --timeout=600s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_rollout
      retries: 3
      delay: 30
      until: rancher_rollout.rc == 0

    - name: Get Rancher pods status
      ansible.builtin.command: kubectl get pods -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_pods
      changed_when: false

    - name: Display Rancher pods
      ansible.builtin.debug:
        msg: "{{ rancher_pods.stdout_lines }}"

    - name: Get Rancher service details
      ansible.builtin.command: kubectl get svc -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_svc
      changed_when: false

    - name: Display Rancher service
      ansible.builtin.debug:
        msg: "{{ rancher_svc.stdout_lines }}"

    - name: Display final installation summary
      ansible.builtin.debug:
        msg: |
          ==========================================
          Rancher Installation Complete!
          ==========================================
          
          Access Rancher UI at: https://{{ rancher_hostname }}
          Username: admin
          Password: {{ rancher_bootstrap_password }}
          
          To access from your local machine:
          1. Add to /etc/hosts on your Mac:
             sudo nano /etc/hosts
             Add line: <VM_IP> {{ rancher_hostname }}
          
          2. Open browser: https://{{ rancher_hostname }}
          
          Note: You will see a certificate warning - this is normal.
          Click 'Advanced' and 'Proceed' to continue.
          ==========================================