---
- name: Install Rancher on Kubernetes
  hosts: control
  become: true
  
  vars:
    rancher_version: "2.9.3"
    cert_manager_version: "v1.14.5"
    rancher_namespace: "cattle-system"
    cert_manager_namespace: "cert-manager"
    rancher_bootstrap_password: "admin"
    
  tasks:
    - name: Get current user
      ansible.builtin.command: whoami
      register: current_user_result
      changed_when: false
      become: false

    - name: Set current user fact
      ansible.builtin.set_fact:
        current_user: "{{ current_user_result.stdout }}"

    - name: Set KUBECONFIG for non-root user
      ansible.builtin.set_fact:
        kubeconfig_path: "/home/{{ current_user }}/.kube/config"
      when: current_user != "root"

    - name: Set KUBECONFIG for root
      ansible.builtin.set_fact:
        kubeconfig_path: "/etc/kubernetes/admin.conf"
      when: current_user == "root"

    - name: Display kubeconfig path
      ansible.builtin.debug:
        msg: "Using KUBECONFIG: {{ kubeconfig_path }}"

    - name: Check if Kubernetes is accessible
      ansible.builtin.command: kubectl get nodes
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: k8s_check
      changed_when: false

    - name: Display Kubernetes status
      ansible.builtin.debug:
        msg: "{{ k8s_check.stdout_lines }}"

    - name: Get external IP from GCP metadata
      ansible.builtin.shell: curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip
      register: external_ip_result
      changed_when: false
      failed_when: false

    - name: Set Rancher hostname with external IP
      ansible.builtin.set_fact:
        rancher_hostname: "{{ external_ip_result.stdout }}.sslip.io"
      when: external_ip_result.rc == 0 and external_ip_result.stdout != ""

    - name: Set default hostname if external IP not found
      ansible.builtin.set_fact:
        rancher_hostname: "rancher.local"
      when: external_ip_result.rc != 0 or external_ip_result.stdout == ""

    - name: Display Rancher hostname
      ansible.builtin.debug:
        msg: "Rancher will be accessible at: https://{{ rancher_hostname }}"

    # Install Helm
    - name: Check if Helm is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/helm
      register: helm_exists

    - name: Download and install Helm
      ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      when: not helm_exists.stat.exists

    - name: Verify Helm installation
      ansible.builtin.command: helm version --short
      register: helm_version_check
      changed_when: false

    - name: Show Helm version
      ansible.builtin.debug:
        msg: "{{ helm_version_check.stdout }}"

    # Add Helm repositories
    - name: Add Rancher Helm repository
      ansible.builtin.shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable || true
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Add Jetstack Helm repository
      ansible.builtin.shell: helm repo add jetstack https://charts.jetstack.io || true
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    # Install cert-manager
    - name: Create cert-manager namespace
      ansible.builtin.shell: kubectl create namespace {{ cert_manager_namespace }} || true
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Install cert-manager CRDs
      ansible.builtin.shell: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Check if cert-manager is already installed
      ansible.builtin.command: helm list -n {{ cert_manager_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_check
      changed_when: false

    - name: Install cert-manager using Helm
      ansible.builtin.shell: |
        helm install cert-manager jetstack/cert-manager \
          --namespace {{ cert_manager_namespace }} \
          --version {{ cert_manager_version }} \
          --wait \
          --timeout 10m
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: "'cert-manager' not in certmanager_check.stdout"

    - name: Wait for cert-manager pods to be ready
      ansible.builtin.shell: |
        kubectl wait --for=condition=ready pod \
          -l app.kubernetes.io/instance=cert-manager \
          -n {{ cert_manager_namespace }} \
          --timeout=300s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_ready
      retries: 3
      delay: 10
      until: certmanager_ready.rc == 0

    - name: Display cert-manager status
      ansible.builtin.command: kubectl get pods -n {{ cert_manager_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: certmanager_pods
      changed_when: false

    - name: Show cert-manager pods
      ansible.builtin.debug:
        msg: "{{ certmanager_pods.stdout_lines }}"

    # Install Rancher
    - name: Create Rancher namespace
      ansible.builtin.shell: kubectl create namespace {{ rancher_namespace }} || true
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: false

    - name: Check if Rancher is already installed
      ansible.builtin.command: helm list -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_check
      changed_when: false

    - name: Install Rancher using Helm
      ansible.builtin.shell: |
        helm install rancher rancher-stable/rancher \
          --namespace {{ rancher_namespace }} \
          --set hostname={{ rancher_hostname }} \
          --set replicas=1 \
          --set bootstrapPassword={{ rancher_bootstrap_password }} \
          --version {{ rancher_version }} \
          --wait \
          --timeout 15m
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: "'rancher' not in rancher_check.stdout"

    - name: Wait for Rancher deployment to be ready
      ansible.builtin.command: kubectl rollout status deploy/rancher -n {{ rancher_namespace }} --timeout=600s
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_rollout
      retries: 3
      delay: 30
      until: rancher_rollout.rc == 0

    - name: Get Rancher pods status
      ansible.builtin.command: kubectl get pods -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_pods
      changed_when: false

    - name: Display Rancher pods
      ansible.builtin.debug:
        msg: "{{ rancher_pods.stdout_lines }}"

    - name: Get all Rancher resources
      ansible.builtin.command: kubectl get all -n {{ rancher_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: rancher_resources
      changed_when: false

    - name: Display final installation summary
      ansible.builtin.debug:
        msg: |
          ==========================================
          Rancher Installation Complete!
          ==========================================
          
          Access Rancher UI:
            URL: https://{{ rancher_hostname }}
            Username: admin
            Password: {{ rancher_bootstrap_password }}
          
          Note: You will see a certificate warning.
          This is normal for self-signed certificates.
          
          After first login:
            1. Set a new secure password
            2. Configure server URL
          ==========================================
